### ISSUE TITLE
How is it supposed to work?

### ISSUE THREAD

**Issue by JonasVautherin** [stejskal/sbt-webpack#6]
I am currently using `sbt-reactjs`, which compiles my `app/assets/javascripts/<file>.jsx` into `target/web/public/main/javascripts/<file>.js`.

The thing is that when I do something like this in my <file>.jsx:

    import App from '.App';

Then I get the following error:

> Parse Error: Line 1: Illegal import declaration

I assume I should run webpack before the compilation made by `sbt-reactjs`. Right?

So I installed your plugin as explained in the readme (except that I am adding `librariyDependencies ++= "org.webjars" % "webpack" % "1.13.1"` instead of your `package.json`), but nothing is happening.

Is there something wrong with `includeFilter in webpack`? What does it mean? How do you use your own plugin?

Thanks in advance!

**Comment by stejskal** [comment]
Hi Jonas, 

You should run sbt-reactjs first and then webpack.

I do not think including the webjar for webpack will work.  My plugin actually shells out to a node instance which will not have any knowledge of the webpack dependency in the build context.

`includeFilter in webpack` is a setting which defines which js files to include in the final webpack file.

I hope this helps.

Spencer
